SELECT * FROM EMPLOYEES e;
SELECT FIRST_NAME FROM EMPLOYEES e;

--1) 모든 사원명과 이메일만 조회
SELECT FIRST_NAME,EMAIL FROM EMPLOYEES e;

--2) 모든 부서의 부서명과 매니져 아이디만 조회
SELECT DEPARTMENT_NAME,MANAGER_ID FROM DEPARTMENTS d;

--3) 컬럼명의 별칭 사용하기 dual(오라클제공 테스트용 가상테이블 컬럼1 로우1) 
SELECT 10 + 10 AS hap FROM dual;

--4) distinct(중복없애기) 사원테이블에서 부서코드를 중복없이 조회(컬럼명을 대체로는 1개만 쓰지만 두개 이상으로 쓸경우에는 두개가 합쳐져 유니크한 값이 된다 -두개의 값이 다 같아야 중복인정-)
SELECT DISTINCT DEPARTMENT_ID, MANAGER_ID FROM EMPLOYEES e;

--5) 사원 테이블의 정보를 아래와 같이 출력하시오.
--   xxx 사원의 부서코드은  xxx입니다.
SELECT first_name||'사원의 부서코드는'||DEPARTMENT_ID||'입니다' AS "NAME AND DEPARTMENT_ID" FROM EMPLOYEES e; 

--6) 급여가 10000원 이상인 직원의 이름과 급여를 조회
SELECT FIRST_NAME,SALARY FROM EMPLOYEES e WHERE SALARY >= 10000;

--7) 급여가 10000원 이상 이거나 4000이하인 직원의 이름,급여,이메일을 조회
SELECT FIRST_NAME,SALARY,EMAIL FROM EMPLOYEES e WHERE SALARY >=10000 OR SALARY <= 4000;

--8) 부서코드가 100번 이거나 급여가 10000원 이상인 직원의 부서코드,이름,급여 조회
SELECT DEPARTMENT_ID,FIRST_NAME,SALARY FROM EMPLOYEES e WHERE DEPARTMENT_ID = 100 OR SALARY >=10000;

--9) 급여가 5000이상이고 7000이하인 직원의 성명,급여를 출력하시오 BETWEEN 이용
--salary >= 5000 and salary <=7000 
SELECT FIRST_NAME,SALARY FROM EMPLOYEES e WHERE SALARY BETWEEN 5000 AND 7000;

--10) 부서아이디가 80 또는 90 또는 100인 직원의 이름 이메일 부서코드
SELECT FIRST_NAME,EMAIL,DEPARTMENT_ID FROM EMPLOYEES e  WHERE DEPARTMENT_ID IN ('80','90','100');

---11) 이름이 S로 시작하는 직원의 아이디, 성명을 조회(LIKE)
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE 'S%';

--12) 이름에 s가 포함되어있는 직원의 아이디 성명을 조회
SELECT EMPLOYEE_ID, FIRST_NAME FROM EMPLOYEES e 
WHERE FIRST_NAME LIKE '%s%';

--13) commission_pct가 있는 직원의 이름과 commission_pet을조회
SELECT FIRST_NAME,COMMISSION_PCT FROM EMPLOYEES e WHERE COMMISSION_PCT  IS NULL;
SELECT FIRST_NAME,COMMISSION_PCT FROM EMPLOYEES e WHERE COMMISSION_PCT  IS NOT NULL;

---14) commission이 있는 직원들은 성명,급여,보너스(급여*commission_pct) 를 조회하시오
SELECT FIRST_NAME AS 성명 ,SALARY AS 급여 ,SALARY*COMMISSION_PCT AS 보너스 FROM EMPLOYEES e WHERE COMMISSION_PCT  IS NOT NULL;
-- 요소 연산 NULL은 NULL
SELECT FIRST_NAME AS 성명 ,SALARY AS 급여 ,SALARY*COMMISSION_PCT AS 보너스 FROM EMPLOYEES e WHERE COMMISSION_PCT  IS NULL;

--15) 급여가 10000원 이상인 직원의 이름,급여를 급여순으로 조회
SELECT FIRST_NAME||LAST_NAME AS 성명,SALARY AS 급여 FROM EMPLOYEES e WHERE SALARY>=10000 ORDER BY SALARY;

--16) 15번 문제에서 동일한 경우에는 이름순으로 정렬을 해보자
SELECT FIRST_NAME||LAST_NAME AS 성명,SALARY AS 급여 FROM EMPLOYEES e WHERE SALARY>=10000 ORDER BY SALARY,FIRST_NAME;